### PR TITLE
Update Terraform SDK to v0.12.0

### LINKED ISSUE #11: Incompatible with Terraform 0.12
Terraform 0.12 seems to have backwards incompatible changes in it, and it refuses to run this plugin with the error 

    Error: Failed to instantiate provider "gandi" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]

### PR DESCRIPTION
**Pull request by duemir**
As per [Terraform 0.12 Compatibility for Providers](https://www.terraform.io/docs/extend/terraform-0.12-compatibility.html). However, I haven't gone through the known issues section.

I ran a plan on the existing infrastructure so only "tested" the refresh of the state.

fixes #11

### CODE REVIEW

**Comment by shomodj** [comment]
any change to get this ASAP?

**Comment by tiramiseb** [comment]
Sorry, I don't have much time these days.
I trust you on this, @duemir ^^'

**Comment by shomodj** [comment]
thanks!

**Comment by jakubgs** [comment]
Any plans to make a `v1.1.0` release or something? Or do I have to build it myself?

**Comment by jakubgs** [comment]
I guess I'll just use the d14e82fd1eadc16162482594e5b24471f58c1507 commit as the target, but a tag would be nice.

**Comment by tiramiseb** [comment]
Oops, I'm very sorry, I forgot to do so.

To be honest, I'm currently planning my wedding, I don't spend much time on any other project...

**Comment by shomodj** [comment]
@tiramiseb congrats!

**Comment by jakubgs** [comment]
Congratulations indeed!

**Pull request merged**
